language: php

php:
  - 7.3
  - 7.4

addons:
  apt:
    packages:
      - rabbitmq-server

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.php-cs-fixer

before_script:
  - mkdir -p build/logs

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.clover
  - if [ $TRAVIS_PHP_VERSION = "7.4" ]; then ./vendor/bin/psalm --config=psalm.xml; fi
  - if [ $TRAVIS_PHP_VERSION = "7.4" ]; then ./vendor/bin/phpstan analyse src --level 7; fi
  - if [ $TRAVIS_PHP_VERSION = "7.4" ]; then ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run; fi

after_script:
  - if [ $TRAVIS_PHP_VERSION = "7.4" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION = "7.4" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

