language: php

php:
  - 7.2
  - 7.3

services:
  - postgresql
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/composer

before_script:
  - mkdir -p build/logs
  - psql -c 'CREATE DATABASE test;' -U postgres

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar
  - chmod +x ocular.phar

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
