language: php

php:
  - 7.4snapshot

addons:
  apt:
    packages:
      - rabbitmq-server

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.php-cs-fixer

before_script:
  - mkdir -p build/logs

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar
  - chmod +x ocular.phar
  - composer show

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.clover
  - ./vendor/bin/psalm --config=psalm.xml
  - ./vendor/bin/phpstan analyse src --level 7
  - ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run

after_script:
  - wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
